// Memory Images Auto-Loader
// Automatically loads all images from the assets/images/memmory/ folder
// This file is auto-generated by scripts/generateImageImports.js

// Auto-generated imports - these are updated by the build script
const imageImports = {
  'IMG-20250814-WA0002.jpeg': require('@/assets/images/memmory/IMG-20250814-WA0002.jpeg'),
  'IMG-20250814-WA0004.jpeg': require('@/assets/images/memmory/IMG-20250814-WA0004.jpeg'),
  'IMG-20250814-WA0006.jpeg': require('@/assets/images/memmory/IMG-20250814-WA0006.jpeg'),
  'IMG-20250814-WA0007.jpeg': require('@/assets/images/memmory/IMG-20250814-WA0007.jpeg'),
  'vacation.jpeg': require('@/assets/images/memmory/vacation.jpeg'),
};

// Export array of all memory images
export const memoryImages = Object.values(imageImports);

// Export images with their filenames for reference
export const memoryImageMap = imageImports;

// Get all available image filenames
export const getImageFilenames = () => Object.keys(imageImports);

// Helper function to get total count
export const getMemoryCount = () => memoryImages.length;

// Helper function to get a specific memory image
export const getMemoryImage = (index: number) => {
  if (index >= 0 && index < memoryImages.length) {
    return memoryImages[index];
  }
  return memoryImages[0]; // fallback to first image
};

// Helper function to get image by filename
export const getMemoryImageByFilename = (filename: string) => {
  return memoryImageMap[filename] || memoryImages[0];
};
